// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUHKxURFCCEitcVY4rA1wiarSV8Cbp3g',
    appId: '1:465285615890:web:dc1842f6ed9af08334e3cb',
    messagingSenderId: '465285615890',
    projectId: 'cash-trace',
    authDomain: 'cash-trace.firebaseapp.com',
    storageBucket: 'cash-trace.firebasestorage.app',
    measurementId: 'G-4L8SMP450Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBFKscRAHHEviBXWbOvT_nk3yzqbFO7A',
    appId: '1:465285615890:android:4acfea22128e440634e3cb',
    messagingSenderId: '465285615890',
    projectId: 'cash-trace',
    storageBucket: 'cash-trace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FPYcxFFhvWK3pkZohoKj65tG4M03B_k',
    appId: '1:465285615890:ios:e959ba9936bb79b734e3cb',
    messagingSenderId: '465285615890',
    projectId: 'cash-trace',
    storageBucket: 'cash-trace.firebasestorage.app',
    iosBundleId: 'com.example.cashTrace',
  );
}
